name: CI

on: [push, pull_request]
jobs:
  test-kramdown2:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, "3.0", "3.1", "3.2"]
        gemfile: [ kramdown2 ]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake test

  test-kramdown1:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7]
        gemfile: [ kramdown1 ]
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake test
